---
assignees:
  - ponfertato
commitMessages:
  graphsUpdate: ':bento:graphs: update'
  readmeContent: ':pencil:README: update'
  statusChange: $EMOJI:$SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms)
  summaryJson: ':card_file_box:summary: update'
owner: potatoenergy
repo: status
sites:
  - method: HEAD
    name: HEAD chat.potatoenergy.ru
    url: https://chat.potatoenergy.ru/health
  - method: HEAD
    name: HEAD cloud.potatoenergy.ru
    url: https://cloud.potatoenergy.ru/ocs/v2.php/apps/serverinfo/api/v1/info
  - method: HEAD
    name: HEAD potatoenergy.ru
    url: https://potatoenergy.ru/sitemap.xml
  - method: HEAD
    name: HEAD social.potatoenergy.ru
    url: https://social.potatoenergy.ru/health
  - check: tcp-ping
    name: mindustry-server
    port: 6567
    url: connect.potatoenergy.ru
  - check: tcp-ping
    name: minecraft-server
    port: 25565
    url: connect.potatoenergy.ru
  - check: tcp-ping
    name: PING connect.potatoenergy.ru
    url: connect.potatoenergy.ru
  - check: tcp-ping
    name: PING potatoenergy.ru
    url: potatoenergy.ru
status-website:
  cname: status.potatoenergy.ru
  logoUrl: https://avatars.githubusercontent.com/u/137938438?s=200&v=4
  name: Potato Energy
user-agent: potatoenergy