owner: potatoenergy
repo: status
sites:
  - name: HEAD chat.potatoenergy.ru
    url: https://chat.potatoenergy.ru/auth
    method: HEAD
  - name: HEAD cloud.potatoenergy.ru
    url: https://cloud.potatoenergy.ru/login
    method: HEAD
  - name: HEAD potatoenergy.ru
    url: https://potatoenergy.ru/search
    method: HEAD
  - name: HEAD social.potatoenergy.ru
    url: https://social.potatoenergy.ru/auth/sign_in
    method: HEAD
  - name: mindustry-server
    check: "tcp-ping"
    url: connect.potatoenergy.ru
    port: 6567
  - name: minecraft-server
    check: "tcp-ping"
    url: connect.potatoenergy.ru
    port: 25565
  - name: PING connect.potatoenergy.ru
    check: "tcp-ping"
    url: connect.potatoenergy.ru
  - name: PING potatoenergy.ru
    check: "tcp-ping"
    url: potatoenergy.ru
commitMessages:
  readmeContent: ":pencil:README: update"
  summaryJson: ":card_file_box:summary: update Update"
  statusChange: "$EMOJI$SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms)"
  graphsUpdate: ":bento:graphs: update"
assignees:
  - ponfertato
user-agent: potatoenergy
status-website:
  cname: status.potatoenergy.ru
  logoUrl: https://avatars.githubusercontent.com/u/137938438?s=200&v=4
  name: Potato Energy
